### ISSUE TITLE
Rebuild to *-testing regularly

### ISSUE THREAD

**Issue by v4hn** [ubi-agni/ros-builder-action#11]
To reduce the number of bottlenecks in this infrastructure it would be desirable to rebuild all changed package versions for a target distribution regularly and deploy them to a deb repository people can access even if the head maintainer does not have the time to retrigger builds.

As discussed with @rhaschke just now, this would require (1) a regularly-scheduled action run in this repository and (2) a regular sync of freshly-built packages to https://ros.packages.techfak.net/dists/ .

#10 is somewhat related.

**Comment by rhaschke** [comment]
On ros.packages.techfak.net run a [FastAPI](https://fastapi.tiangolo.com) server to handle GET requests from github.

**Comment by rhaschke** [comment]
I (almost) managed to automatically sync built packages to https://ros.packages.techfak.net. The only remaining issue is entering the signature passphrase required by reprepro. I tried using `gpg-preset-passphrase`:
https://github.com/ubi-agni/ros-builder-action/blob/4ef104c9bee537447d7948a70edfc26d48803521/reprepro/server.sh#L11-L13
but that doesn't work yet. Any ideas @jspricke? I'm afraid, I'm passing the wrong `$GPG_KEY`. Should that be the string used for `SignWith` in reprepro's `conf/distributions` file or something else?

The following commands return different magic numbers:
```
gpg --list-secret-key --with-subkey-fingerprint  # 'ssb' field used for reprepro's SignWith field
gpg --list-secret-keys --with-keygrip
```
