### ISSUE TITLE
Instruction to add ROS2 APT repository removed 

### ISSUE THREAD

**Issue by ojura** [ubi-agni/ros-builder-action#13]
@rhaschke an instruction to add the ROS2 repo has been removed from https://ros.packages.techfak.net/.

Trying to follow the instructions on Ubuntu 24.04 results in getting stuck at installing python3-rosdep, because the package is missing.

Should the users still add the repository? Have you intentionally removed this step?

**Comment by rhaschke** [comment]
Yes, I intentionally removed the ROS2 repo as the corresponding rosdep packages are imported into the Jammy distro.
I added the packages to the noble distro as well now. Please tell me, if there are more packages missing.

**Comment by ojura** [comment]
Thanks. Yes, there is a couple more missing:

```
The following packages have unmet dependencies:
 python3-rosdep-modules : Depends: python3-rospkg-modules (>= 1.4.0) but it is not installable
                          Depends: python3-catkin-pkg-modules (>= 0.4.0) but it is not installable
                          Depends: python3-rosdistro-modules (>= 0.7.5) but it is not installable
```

**Comment by rhaschke** [comment]
Please try again. I added them.

**Comment by ojura** [comment]
This fixes it. Thanks!

Btw, I suggest adding a line to install curl to the instructions. It is not installed by default on Ubuntu, and some novice users might need the instruction to install it.
