### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by ojura** [ubi-agni/ros-builder-action#15]
I spinned up a Gitlab runner on an arm64 Ubuntu 22.04. The following is probably the most important change needed to get the [pipeline](https://github.com/larics/ros-builder-action/actions/runs/11331298615/job/31516509719) to run on arm64:

```diff
@@ -77,10 +77,10 @@ if debian-distro-info --all | grep -q "$DEB_DISTRO"; then
 	export DISTRIBUTION_REPO=http://deb.debian.org/debian
 	ici_append INSTALL_HOST_GPG_KEYS "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E98404D386FA1D9 6ED0E7B82643E131 F8D2585B8783D481"
 
 elif ubuntu-distro-info --all | grep -q "$DEB_DISTRO"; then
 	export DISTRIBUTION=ubuntu
-	export DISTRIBUTION_REPO=http://azure.archive.ubuntu.com/ubuntu
+	export DISTRIBUTION_REPO=http://ports.ubuntu.com/ubuntu-ports
 else
 	gha_error "Unknown DEB_DISTRO: $DEB_DISTRO"
 	ici_exit 1
 fi
```

Github is supposed to receive support for free arm64 runners soonish. Maybe we could spin a free one in the Oracle cloud?

**Comment by rhaschke** [comment]
Thanks for your feedback. This is related to #9.

> I spinned up a Gitlab runner on an arm64 Ubuntu 22.04.

What does that mean exactly? Do you have a local runner or a cloud one? 
Did you manage to register it as an external github runner?
Did you already build ARM64 packages? If so, can you provide the .debs (or the github artifact) for upload on https://ros.packages.techfak.net?

**Comment by ojura** [comment]
The process of adding a runner is pretty simple. Go to https://github.com/ubi-agni/ros-builder-action/settings/actions/runners,
hit New runner, and you will get the command line for configuring the runner an arm64 Ubuntu. 

I don't have the debs yet because the OOM killer is interrupting the process; will update.

**Comment by ojura** [comment]
By the way, unrelated question - when I re-run the interactive action, `sudo rosdep init` fails for me and I have to `sudo rm /etc/ros/rosdep/sources.list.d/20-default.list` (it complains that the file exists). How do you avoid this on your runner?

**Comment by rhaschke** [comment]
> When I re-run the interactive action, `sudo rosdep init` fails.

I never experienced this issue. The default runner always runs on a clean image though.

> The process of adding a runner is pretty simple.

I know. But I don't have an ARM device available as a runner. I'm looking forward to receive your debs.

**Comment by rhaschke** [comment]
Thanks for providing the debs for Noble ARM64. I uploaded them to ros.packages.techfak.net.

`NoSimTime` was only recently introduced in release 1.17.0 of [`ros_comm`](https://github.com/ros/ros_comm), which I didn't yet include in my .repos file. Rebuilding with `Continue previous build?` enabled should fix that.

Do you mind running an ARM64 build for Jammy as well?

**Comment by ojura** [comment]
Thanks!

Here is the latest pipeline where more stuff (like nodelet and rviz) passed the build:

https://github.com/larics/ros-builder-action/actions/runs/11355371578

**Comment by ojura** [comment]
@rhaschke I don't think you can have a `choice` in a reusable task:

```diff
@@ -12,17 +12,14 @@ on:
       DEB_DISTRO:
         type: string
         description: The Debian/Ubuntu distribution codename to compile for
         required: false  # defaults to 'lsb_release -cs'
       ARCH:
-        type: choice
+        type: string
         required: true
         description: CPU architecture
         default: x64
-        options:
-          - x64
-          - arm64
       ROS_SOURCES:
         type: string
         description: ROS sources to compile. See README.md for details.
         required: false
       COLCON_PKG_SELECTION:
```

```
The workflow is not valid. In .github/workflows/interactive.yaml (Line: 67, Col: 11): Error from called workflow larics/ros-builder-action/.github/workflows/build.yaml@main (Line: 17, Col: 15): Unexpected value 'choice' In .github/workflows/interactive.yaml (Line: 67, Col: 11): Error from called workflow larics/ros-builder-action/.github/workflows/build.yaml@main (Line: 21, Col: 9): Unexpected value 'options'
```

**Comment by ojura** [comment]
Thanks, I see. The runner is a bit slow, so I yanked the failing packages out to reduce build time.

> All packages are staged to distro noble now as well.

Ah, I've never fully understood what exactly it means to stage packages in Debian, although I've seen that countless times. :eyes:

**Comment by ojura** [comment]
About your changes to `env.sh`:

1) a pipe delimits multiple cases, i.e. `arm64|armhf)`
2) I got an unbounded variable error for `$ARCH`. And it makes more sense to print the input to the switch anyway (`gha_error "Unknown architecture: $(dpkg --print-architecture)"`). `ARCH` should only be used at the Github-level to pick a runner, right?

**Comment by rhaschke** [comment]
Great. Looks like the jammy build is running now: https://github.com/larics/ros-builder-action/actions/runs/11364563242

**Comment by ojura** [comment]
Indeed it's running. Although, this one is a Amazon AWS t4g.small runner with 2 cpus and 2 gigs of RAM (available for free until the end of the year) so it's going to take a while.

BTW: any chance you could add gmapping to the build?

**Comment by ojura** [comment]
> Great. Looks like the jammy build is running now: https://github.com/larics/ros-builder-action/actions/runs/11364563242

This one was cancelled due to the 6h limit in main.js; restarted https://github.com/larics/ros-builder-action/actions/runs/11370576748/job/31630680071

**Comment by ojura** [comment]
@rhaschke arm64 jammy artifacts available at
https://github.com/larics/ros-builder-action/actions/runs/11386914003

**Comment by rhaschke** [comment]
Thanks, I imported them to ros.packages.techfak.net.

@jspricke: The fcl build is failing due `SSE` build options:
https://github.com/larics/ros-builder-action/actions/runs/11370576748/job/31630680071#step:5:4705
Why fcl/sbuild are using those x64 options?

**Comment by jspricke** [comment]
I guess due to:

<https://github.com/flexible-collision-library/fcl/blob/master/CMakeLists.txt#L84>

**Comment by rhaschke** [comment]
But there is also a test if SSE is supported:
https://github.com/flexible-collision-library/fcl/blob/master/CMakeLists.txt#L96-L98

**Comment by jspricke** [comment]
>@jspricke: Is it possible to pass cmake options via sbuild (and thus disable SSE)?

sbuild only calls dpkg-buildpackage. The right interface is the 
debian/rules file generated by bloom. You can patch it like this:

https://sources.debian.org/src/fcl/0.7.0-3/debian/rules/#L26

**Comment by v4hn** [comment]
> @v4hn: You don't build fcl and octomap. Do you use the system-provided ones?

Yes, I rely on the Debian packages for both at the moment. If there are reasons to build them independently again in Ubuntu 22.04 and newer, I would be interested to know.

**Comment by jspricke** [comment]
fyi you can also get free arm compute from Oracle (maybe longer then AWS): https://www.oracle.com/cloud/compute/arm/

**Comment by rhaschke** [comment]
Thanks for the hint. Will have a look at some point... 
@ojura: What did you do for setting up your runner? Do you have a Dockerfile or similar, which you can share?

**Comment by ojura** [comment]
@rhaschke I had trouble with getting to run schroot in Docker. But here's roughly what you need to do to get it running on a vanilla Ubuntu image.

```bash
sudo apt update
sudo apt dist-upgrade 
mkdir actions-runner && cd actions-runner
sudo apt install -y curl
curl -o actions-runner-linux-arm64-2.320.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-arm64-2.320.0.tar.gz
tar xzf ./actions-runner-linux-arm64-2.320.0.tar.gz
./bin/installdependencies.sh 
mkdir /home/ubuntu/debs
sudo apt install -y distro-info
sudo apt install -y wget curl gnupg
sudo apt install -y lsb-release git build-essential
 cd /
sudo fallocate --length 12G swap.img
sudo mkswap swap.img 
sudo chmod 0600 swap.img 
sudo swapon swap.img
cd ~/actions-runner/
./config.sh --url https://github.com/larics/ros-builder-action --token XXXXXXXXXXXXXXXXXXXXX
```

And then I ran the runner in tmux. To make it proper you should write a systemd service to run it at startup, and add the swap file to fstab.

**Comment by rhaschke** [comment]
I registered with the Oracle cloud. However, their ARM compute machines are essentially not available / fully in use.
I tried to create a VM dozens of times last days, but always got rejected.

**Comment by rhaschke** [comment]
I'm hesitating doing this...

**Comment by ojura** [comment]
@rhaschke here is a noble pipeline (took ~2 days) which built a lot of your recently imported packages. Eigenpy -j2 is too much for the Amazon worker; I had managed to build it previously by suspending one compiler job with SIGSTOP and letting the other run. I didn't do it this time.

https://github.com/larics/ros-builder-action/actions/runs/11442159906

BTW, would you mind If I asked you to stop force pushing? :) It creates quite a mess for your downstream.

**Comment by rhaschke** [comment]
> Here is a noble pipeline (took ~2 days) which built a lot of your recently imported packages

Thanks a lot. I imported those packages to the package repo.

> Eigenpy -j2 is too much for the Amazon worker.

Looks like we need to allow different sbuild options for different architectures.



> Would you mind If I asked you to stop force pushing?

Sure. Sorry for the inconvienence.

**Comment by ojura** [comment]
> Looks like we need to allow different sbuild options for different architectures.

Alright. One other improvement I would suggest is to disable downloading/uploading cache and downloading debs in case of a persistent runner. It can blow through 100 GB of free AWS traffic quite quickly :sweat_smile:

**Comment by rhaschke** [comment]
> I would suggest is to disable downloading/uploading cache and downloading debs in case of a persistent runner.

I implemented this in https://github.com/ubi-agni/ros-builder-action/commit/f8c7e22bafe49d16be6f06f6b02d4bbc467c47f9.

**Comment by rhaschke** [comment]
I've got an own arm64 runner hosted by Oracle now. Closing this issue.

**Comment by ojura** [comment]
Awesome! Do you have any tips how you set it up? PAYG account? I think billing was totally broken for me because I selected Italy as my primary domain.

**Comment by rhaschke** [comment]
Yes, I upgraded to a PAYG account. I hope it will stay free...
