### ISSUE TITLE
ros-one-usb-cam not visible with apt

### ISSUE THREAD

**Issue by ojura** [ubi-agni/ros-builder-action#19]
@rhaschke you might want to update the packages list for Noble. I see `https://ros.packages.techfak.net/pool/main/r/ros-one-usb-cam/ros-one-usb-cam_0.3.7-19noble.20241023.1756_amd64.deb`, but it seems it's not in the package list. Downloading and installing the deb works fine.

**Comment by rhaschke** [comment]
This package is only available in `noble-testing`. Not sure when to sync those to `noble`.

**Comment by ojura** [comment]
Ah, okay! Do you think it would make sense to  reference the testing component in install instructions on the landing page, so users are aware and can opt in?

**Comment by rhaschke** [comment]
It is already mentioned:

> ### Cutting edge testing repository
> In order to use latest builds as soon as they become available, you can use the -testing repository. Just replace `$(lsb_release -cs)` above with `$(lsb_release -cs)-testing`.
