### ISSUE TITLE
teleop_twist_keyboard package missing

### ISSUE THREAD

**Issue by ojura** [ubi-agni/ros-builder-action#6]
Any chance the teleop_twist_keyboard package ([https://github.com/ros-teleop/teleop_twist_keyboard.git](https://github.com/ros-teleop/teleop_twist_keyboard)) can be added to the build list? 

Cloning it manually into a workspace and building works, it’s really a minor inconvenience not to have it available as an installable package. I think it’s a fairly important base functionality package, it would be nice to have it.

**Comment by rhaschke** [comment]
Done
